add solution 04-02-skeleton
js-tasks-ru/htmlcss-20210812_marato13 pull request #10
Opened 2021-08-21 18:19 UTC by maratabdulin

2021-08-21 18:19 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-08-23 13:08 UTC, GSemikozov requested changes

2021-08-23 13:08 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +	width: 579px;
ширину и высоту лучше не фиксировать

2021-08-23 13:08 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton__line1 {
.skeleton__line1 и .skeleton__line2 - не очень информативные классы, которые при этом еще и нельзя переиспользовать. Предлагаю использовать .skeleton__line, как общий класс для группы из 2х линий, а там где нужны какие-то модификации (скорее всего с отступами) - можно добавить модификатор

2021-08-23 13:08 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +	height: 50%;
высоту задавать не надо - высота будет определяться внутренним содержимым

2021-08-23 13:08 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton__line2 {
для линий тоже желательно добавить более семантичные классы, например общий будет .skeleton__line, и у него будут модификаторы - модифицируем ширину, поэтому обозначим это и в названии класса, например .skeleton__line_short или .skeleton__line_width50

2021-08-23 13:08 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton__item1 {
это аватар? кстати, из названия класса совсем неясно, и вот почему важно задавать более информативные классы. Если это аватар - можно задать класс .skeleton__avatar или .skeleton__circle, размеры такого круга можно указать фиксированные

2021-08-23 20:07 UTC, maratabdulin commented on 04-lection2/02-skeleton/skeleton.css
> +	height: 50%;
убрал ширину и высоту

2021-08-23 20:07 UTC, maratabdulin commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton__line2 {
изменил названия классов

2021-08-23 20:08 UTC, maratabdulin commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton__item1 {
изменил названия классов и задал фиксированную высоту аватару

2021-08-25 16:25 UTC, GSemikozov approved these changes

2021-08-25 16:25 UTC, merged