add solution of tooltip lession
js-tasks-ru/htmlcss-20210812_marato13 pull request #12
Opened 2021-08-29 11:27 UTC by maratabdulin

2021-08-29 11:28 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-08-29 13:55 UTC, GSemikozov requested changes

2021-08-29 13:55 UTC, GSemikozov commented on 05-lection3/01-tooltip/index.html
> +            <object data="../../assets/images/tooltip.svg" type="image/svg+xml">
в данном случае нет смысла использовать object - либо svg, либо svg-sprite

2021-08-29 14:40 UTC, maratabdulin commented on 05-lection3/01-tooltip/index.html
> +            <object data="../../assets/images/tooltip.svg" type="image/svg+xml">
Я пытался вставить картинку через svg / defs / symbol и в браузере ничего не отображалось. Пути к файлу проверил. А с obgect все работает

2021-08-30 19:59 UTC, GSemikozov commented on 05-lection3/01-tooltip/index.html
> +            <object data="../../assets/images/tooltip.svg" type="image/svg+xml">
если svg - можно указать спецификацию на теге svg xmlns="http://www.w3.org/2000/svg"

2021-08-30 19:59 UTC, GSemikozov commented on 05-lection3/01-tooltip/index.html
> +            <object data="../../assets/images/tooltip.svg" type="image/svg+xml">
лучше довести вариант с свг до рабочего отояния)

2021-09-02 13:37 UTC, GSemikozov approved these changes

2021-09-02 13:37 UTC, merged