Добавил страницу Simple Example Web App
js-tasks-ru/htmlcss-20210812_marato13 pull request #15
Opened 2021-08-31 19:46 UTC by maratabdulin

2021-08-31 19:46 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-09-01 19:54 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-09-02 13:36 UTC, GSemikozov requested changes

2021-09-02 13:36 UTC, GSemikozov commented on components/card/card.css
> +	padding-bottom: 92px;
в карточке ведь нет кнопок, только тайтл и дескрипшн

2021-09-02 13:36 UTC, GSemikozov commented on components/header/header.css
> +.header__component {
должен быть модификатор, то есть .header_component

2021-09-02 13:36 UTC, GSemikozov commented on components/header/header.css
> +	.header__mobile-menu {
если это кнопка вызова меню, то предлагаю подкорректировать класс - .header__open-mobile-menu-btn или просто .header__burger

2021-09-02 13:36 UTC, GSemikozov commented on components/main-component/main-component.css
> +.main__window {
а этот window точно обязателен? если это просто секция в которой описывается компонент - логичнее как-нибудь так и назвать, например  просто .main__component-overview

2021-09-02 19:29 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-09-04 11:21 UTC, maratabdulin commented on components/main-component/main-component.css
> +.main__window {
поправил

2021-09-04 11:21 UTC, maratabdulin commented on components/card/card.css
> +	padding-bottom: 92px;
перенес класс в preview.css и заменил название на preview__footer

2021-09-04 11:21 UTC, maratabdulin commented on components/header/header.css
> +.header__component {
заменил

2021-09-04 11:21 UTC, maratabdulin commented on components/header/header.css
> +	.header__mobile-menu {
заменил на .header__burger

2021-09-04 11:23 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-09-04 16:00 UTC, GSemikozov approved these changes

2021-09-04 16:00 UTC, merged