add preview and tab element
js-tasks-ru/htmlcss-20210812_marato13 pull request #23
Opened 2021-09-08 20:02 UTC by maratabdulin

Не разобрался как через css сделать чтобы скрывались и показывались элементы по изменению в табах.

2021-09-08 20:02 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-09-09 09:35 UTC, GSemikozov requested changes

2021-09-09 09:35 UTC, GSemikozov commented on components/tabs/tabs.css
> +.tabs__container:hover > .tabs__title {
hover лучше делать только у label

2021-09-09 09:35 UTC, GSemikozov commented on index.html
> +        <div class="tabs">
при такой реализации не вижу как будут работать табы и отображаться контент табов)

2021-09-20 20:19 UTC, closed without merging